Update tests workflow

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -1,10 +1,8 @@
-name: Java Tests and Coverage
+name: Tests and Coverage
 
 on:
-  push:
-    branches: [ main ]
-  pull_request:
-    branches: [ main ]
+  workflow_dispatch:
+
 
 jobs:
   build:
@@ -16,7 +14,7 @@ jobs:
     - name: Set up JDK 17
       uses: actions/setup-java@v4
       with:
-        java-version: '17'
+        java-version: '17`'
         distribution: 'adopt'
 
     - name: Cache Maven packages
@@ -26,8 +24,14 @@ jobs:
         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
         restore-keys: ${{ runner.os }}-m2
 
-    - name: Build and run tests with Maven
-      run: mvn clean verify org.jacoco:jacoco-maven-plugin:report
+    - name: Build with Maven
+      run: mvn clean compile
+
+    - name: Run tests
+      run: mvn test
+
+    - name: Generate JaCoCo Coverage Report
+      run: mvn jacoco:report
 
     - name: Upload coverage report
       uses: actions/upload-artifact@v4
@@ -43,10 +47,15 @@ jobs:
         min-coverage-overall: 80
         min-coverage-changed-files: 80
 
-    - name: Fail if coverage is less than 80%
+    - name: Check coverage percentage
       run: |
         COVERAGE=$(grep -oP 'Total.*?([0-9]{1,3})%' target/site/jacoco/index.html | grep -oP '[0-9]{1,3}')
-        if [ "$COVERAGE" -lt 80 ]; then
+        if [ -z "$COVERAGE" ]; then
+          echo "Failed to extract coverage percentage"
+          exit 1
+        elif [ "$COVERAGE" -lt 80 ]; then
           echo "Test coverage is below 80%. Current coverage: $COVERAGE%"
           exit 1
+        else
+          echo "Test coverage is $COVERAGE%"
         fi
